version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    networks:
      - ems-net

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - ems-net
    depends_on:
      - backend

networks:
  ems-net:
